import { MarketInstrument } from "./types";

export const MARKET_REGISTRY: MarketInstrument[] = [
  {
    symbol: "EURUSD",
    displayName: "EUR/USD",
    assetClass: "forex",
    category: "major",
    baseCurrency: "EUR",
    quoteCurrency: "USD",
    priority: 5,
    tradingSessions: ["london", "new-york"],
    tradingDays: [1, 2, 3, 4, 5],
    supportedPlans: ["trial", "starter", "pro", "elite"],
    trialEnabled: true,
    pulseModules: [
      "technical",
      "fundamental",
      "macro",
      "sentiment",
      "liquidity",
    ],
  },

  {
    symbol: "GBPUSD",
    displayName: "GBP/USD",
    assetClass: "forex",
    category: "major",
    baseCurrency: "GBP",
    quoteCurrency: "USD",
    priority: 5,
    tradingSessions: ["london", "new-york"],
    tradingDays: [1, 2, 3, 4, 5],
    supportedPlans: ["trial", "starter", "pro", "elite"],
    trialEnabled: true,
    pulseModules: [
      "technical",
      "fundamental",
      "macro",
      "sentiment",
      "liquidity",
    ],
  },

  {
    symbol: "USDJPY",
    displayName: "USD/JPY",
    assetClass: "forex",
    category: "major",
    baseCurrency: "USD",
    quoteCurrency: "JPY",
    priority: 4,
    tradingSessions: ["tokyo", "london"],
    tradingDays: [1, 2, 3, 4, 5],
    supportedPlans: ["starter", "pro", "elite"],
    trialEnabled: false,
    pulseModules: [
      "technical",
      "fundamental",
      "macro",
      "sentiment",
      "liquidity",
    ],
  },

  {
    symbol: "XAUUSD",
    displayName: "Gold",
    assetClass: "metal",
    category: "metal",
    priority: 5,
    tradingSessions: ["london", "new-york"],
    tradingDays: [1, 2, 3, 4, 5],
    supportedPlans: ["trial", "pro", "elite"],
    trialEnabled: true,
    pulseModules: [
      "technical",
      "fundamental",
      "macro",
      "sentiment",
      "liquidity",
    ],
  },

  {
    symbol: "US30",
    displayName: "US30",
    assetClass: "index",
    category: "index",
    priority: 5,
    tradingSessions: ["new-york"],
    tradingDays: [1, 2, 3, 4, 5],
    supportedPlans: ["pro", "elite"],
    trialEnabled: false,
    pulseModules: [
      "technical",
      "fundamental",
      "macro",
      "sentiment",
      "liquidity",
    ],
  },

  {
    symbol: "BTCUSD",
    displayName: "Bitcoin",
    assetClass: "crypto",
    category: "crypto",
    priority: 4,
    tradingSessions: [
      "sydney",
      "tokyo",
      "london",
      "new-york",
    ],
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    supportedPlans: ["elite"],
    trialEnabled: false,
    pulseModules: [
      "technical",
      "sentiment",
      "macro",
    ],
  },
];