-- ============================================================
-- SmartPulse
-- Harden legal acceptance creation
-- ============================================================

-- The authenticated Supabase user automatically owns
-- every acceptance record they create.
alter table public.legal_acceptances
alter column user_id
set default auth.uid();

-- Remove unrestricted INSERT access.
revoke insert
on table public.legal_acceptances
from authenticated;

-- The client may supply only the versions it is acknowledging.
--
-- id is generated by PostgreSQL.
-- user_id comes from auth.uid().
-- accepted_at comes from the database clock.
grant insert (
  terms_version,
  privacy_version,
  risk_disclosure_version
)
on table public.legal_acceptances
to authenticated;